### ISSUE TITLE
timeline syntax

### ISSUE THREAD

**Issue by andykais** [andykais/ffmpeg-templates#5]
## investigate
- [ ] keypoints
```yaml
clips:
  - file: 'something.mp4'
    trim:
       start: '0.4'
       variable_length: 'end'
    keypoints:
      - name: important_moment
        timestamp: '4.5'
  - file: something_else.mp4
    keypoints:
      - name: important_moment
        timestamp: '1.0'
# InputError when two keypoints cant be matched.
# E.g. one clip has a start time too far away,
# or a end time too short to meet the keypoint

timeline:
  - id: CLIP_0
  - id: CLIP_1
```
- [ ] variable declarations
```yaml
duration_vars:
  clip_0_important_moment: '0.5'
```
- [ ] timeline tree
```yaml
timeline:
  - id: CLIP_0
    next:
      - id: CLIP_1
  - id: CLIP_2
   next:
      - id: CLIP_3
```
